# Generated by Django 4.2.3 on 2023-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='uploaded_image')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
