# Generated by Django 4.2.3 on 2023-09-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(null=True, upload_to='uploaded_image'),
        ),
    ]
